version: "3.8"
services:
  aftas_db:
    image: mysql:8.2.0
    restart: always
    ports:
      - "3307:${MYSQL_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  aftas_api:
    build:
      context: ./Aftas-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: aftas_db
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - aftas_db

  aftas_front:
    build:
      context: ./Aftas-angular
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - aftas_api