version: "3.8"
services:
  aftas_db:
    image: mysql:8.2.0
    restart: always
    ports:
      - "3307:${MYSQL_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - aftas_network

  aftas_api:
    build:
      context: dockerfiles
      dockerfile: api.Dockerfile
      args:
        - REPO_LINK=${API_REPO}
        - REPO_BRANCH=${API_BRANCH}
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: aftas_db
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - aftas_db
    networks:
      - aftas_network

  aftas_front:
    build:
      context: dockerfiles
      dockerfile: frontend.Dockerfile
      args:
        - REPO_LINK=${FRONTEND_REPO}
        - REPO_BRANCH=${FRONTEND_BRANCH}
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - aftas_api
    networks:
      - aftas_network

networks:
  aftas_network:
    driver: bridge